name: ireporter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  provider: ^6.1.1
  get_it: ^7.6.7
  flutter_spinkit: ^5.2.0
  flutter_screenutil: ^5.9.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  oktoast: ^3.4.0
  flutter_smart_dialog: ^4.9.6
  hooks_riverpod: ^2.4.9
  like_button: ^2.0.5
  story: ^1.1.0
  story_view: ^0.16.0
  permission_handler: ^11.2.0
  flutter_chat_bubble: ^2.0.2
  loading_overlay: ^0.3.0
  ionicons: ^0.2.2
  shared_preferences: ^2.2.2
  timeago: ^3.6.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  animations: ^2.0.11
  percent_indicator: ^4.2.3
  google_sign_in: ^6.2.1
  cached_network_image: ^3.3.1
  uuid: ^4.3.3
  image_cropper: ^5.0.1
  video_compress_ds: ^3.1.6
  file_picker: ^6.1.1
  flutter_image_compress: ^2.1.0
  url_launcher: ^6.2.4
  talker_flutter: ^3.6.0
  share_plus: ^7.2.1
  get_time_ago: ^1.3.1
  rive: ^0.12.4
  flutter_linkify: ^6.0.0
  intl: ^0.18.1
  better_player: ^0.0.63
  flutter_animate: ^4.4.0
  flutter_svg: ^2.0.9
  photo_view: ^0.14.0
  connectivity_plus: ^5.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0

flutter:

 
  uses-material-design: true

 
  assets:
    - assets/images/
   